name: daeem
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.1.0
  cloud_firestore: ^2.5.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.1.0
  # Firebase packages
  firebase_core: ^1.6.0
  firebase_dynamic_links: ^2.0.9
  firebase_messaging: ^10.0.7

  #auth
  flutter_facebook_auth: ^3.5.1
  flutter_local_notifications: ^8.2.0
  flutter_localizations:
    sdk: flutter


  flutter_verification_code: ^1.1.0
  google_fonts: ^2.1.0
  google_maps_flutter: ^2.0.10
  google_sign_in: ^5.1.0
  http: ^0.13.3
  intl: ^0.17.0
  introduction_screen: ^2.1.0
  provider: ^6.0.0
  shared_preferences: ^2.0.6
  shimmer: ^2.0.0
  simple_connection_checker: ^0.2.1
  ionicons: ^0.1.2
  geolocator: 7.6.2
  geocoding: ^2.0.1
  top_snackbar_flutter: ^1.0.1
  expandable_bottom_sheet: ^1.1.1+1
  flutter_datetime_picker: ^1.5.1
  flutter_launcher_icons: "^0.9.2"
  location: ^4.3.0
  timelines: ^0.1.0
  sqflite: ^2.0.0+4
  in_app_review: ^2.0.3
  share_plus: ^3.0.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  generate: true
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/background.png
    - assets/logo.png
    - assets/shopping_cart.png
    - assets/order_arrived.png
    - assets/ontheway.png
    - assets/Empty.png
    - assets/market.png
    - assets/Facebook.png
    - assets/Google.png 
    - assets/logo_v.png  
    - assets/closed.png
    - assets/email_sent.png
    - assets/cart.png
    - assets/confirmed.png
    - assets/offline.png
    - assets/placeholder.png
    - assets/empty_cart.png
    - assets/delivery_address.gif
    - assets/sms.gif
    - assets/closed_stores.gif
    - assets/pin.png
    - assets/location.png
    - assets/notification.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-animages/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
#
#
#
